version: '3.8'

services:
  basic-api-dotnet:
    image: basic-api-dotnet:latest
    build: .
    ports:
      - "5000:5000"
      - "80:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"