version: '3'

services:
  basic-api-dotnet:
    image: "${DOCKER_HUB_USERNAME}/basic-api-dotnet:latest"
    ports:
      - "5000:5000"
      - "80:5000"
    environment:
      ASPNETCORE_ENVIRONMENT: "Production"