name: Docker-build-push
on:
  push:
    branches: [master, basic-api]
jobs:
  build-tag-push-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build images
        run: docker-compose -f "docker-compose.yml" up -d --build
      - name: Tag image
        run: docker tag basic-api-dotnet:latest ${{ secrets.DOCKER_HUB_USERNAME }}/basic-api-dotnet:latest
      - name: Push image
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/basic-api-dotnet:latest
      - name: Stop containers
        if: always()
        run: docker-compose -f "docker-compose.yml" down